config/routes.rb
Rails.application.routes.draw do
  # get 'reviews/new'

  # get 'restaurants/index'

  # get 'restaurants/new'

  # get 'restaurants/edit'

  # get 'restaurants/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :restaurants do
      resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]

  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: CATEGORIES, allow_nil: false }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, inclusion: { in: [1,2,3,4,5], allow_nil: false }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    # no need for app/views/restaurants/destroy.html.erb
    redirect_to restaurants_path
  end

    private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone, :category)
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :set_restaurant

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'new'
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
  <div class="container">
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <%= yield %>
      </div>
    </div>
  </div>

  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone %>
  <%= f.select :category, Restaurant::CATEGORIES %>
  <div class="form-group">
    <%= f.submit 'Save', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>
<%= render 'form' %>

app/views/restaurants/index.html.erb
<%= link_to "Add new restaurant", new_restaurant_path %>
<h1>The Restaurants Guide</h1>
<br>
<% @restaurants.each do |restaurant| %>
  <h2> <%= link_to restaurant.name, restaurant_path(restaurant) %> </h2>
<% end %>

app/views/restaurants/new.html.erb
<h1>Restaurants#new</h1>
<%= render 'form' %>

app/views/restaurants/show.html.erb
<%= link_to "Delete", restaurant_path(@restaurant),
      method: :delete,
      data: { confirm: "Are you sure?" } %>
<%= link_to "Home", restaurants_path %>
<%= link_to "Edit", edit_restaurant_path(@restaurant) %>
<%= link_to "Add Review", new_restaurant_review_path(@restaurant.id) %>

<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone %></p>
<p><%= @restaurant.category %></p>
 <h3>Reviews</h3>
<% @restaurant.reviews.each do |review| %>
<p><%= review.rating  %></p>
<p><%= review.content  %></p>
<% end %>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.select :rating, %W(1 2 3 4 5) %>

  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/new.html.erb
<h1>New review for <%= @restaurant.name %></h1>
<%= render 'form' %>